const products = [
  {
    name: "pancake",
    isDiscounted: true,
    isNew: false,
    isRecentlybought: false,
    imgAdress: "/images/pancake.jpg",
    newPrice: "44,50 ₽",
    originalPrice: "50,50 ₽",
    info: "Г/Ц Блинчики с мясом вес, Россия",
    rating: 4.5,
  },
  {
    name: "milk",
    isDiscounted: true,
    isNew: true,
    isRecentlybought: true,
    imgAdress: "/images/milk.jpg",
    newPrice: "44,50 ₽",
    originalPrice: "50,50 ₽",
    info: "Молоко ПРОСТОКВАШИНО паст. питьевое цельное отборное...",
    rating: 3,
  },
  {
    name: "salami",
    isDiscounted: true,
    isNew: true,
    isRecentlybought: false,
    imgAdress: "/images/salami.jpg",
    newPrice: "44,50 ₽",
    originalPrice: "50,50 ₽",
    info: "Колбаса сырокопченая МЯСНАЯ ИСТОРИЯ Сальчичон и Тоскан...",
    rating: 5,
  },
  {
    name: "sausage",
    isDiscounted: true,
    isNew: true,
    isRecentlybought: true,
    imgAdress: "/images/sausage.jpg",
    newPrice: "44,50 ₽",
    originalPrice: "50,50 ₽",
    info: "Сосиски вареные МЯСНАЯ ИСТОРИЯ Молочные и С сыро...",
    rating: 4.5,
  },
  {
    name: "kolbasa",
    isDiscounted: false,
    isNew: true,
    isRecentlybought: true,
    imgAdress: "/images/kolbasa.jpg",
    originalPrice: "599,99 ₽",
    info: "Комбайн КЗС-1218 «ДЕСНА-ПОЛЕСЬЕ GS12»",
    rating: 2,
  },
  {
    name: "vetchina",
    isDiscounted: false,
    isNew: false,
    isRecentlybought: true,
    imgAdress: "/images/vetchina.jpg",
    originalPrice: "77,99 ₽",
    info: "Комбайн КЗС-1218 «ДЕСНА-ПОЛЕСЬЕ GS12»",
    rating: 2,
  },
];

export default products;
